In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
df = pd.read_csv('data/COVID19MEXICO2020.csv')

C:\Users\daniel\AppData\Local\Temp\ipykernel_7736\3166083153.py:1: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/COVID19MEXICO2020.csv')

In [4]:
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,EDAD,NACIONALIDAD,EMBARAZO,HABLA_LENGUA_INDIG,INDIGENA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-10-31,z4d6fe,1,6,24,1,24,24,28,1,2020-12-06,2020-11-30,9999-99-99,97,2,55,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
1,2021-10-31,z2a3cf,1,6,24,2,24,24,28,1,2020-02-20,2020-02-18,9999-99-99,97,2,59,1,97,2,2,2,2,2,2,2,2,2,2,2,2,1,2,97,2,97,6,99,México,97,97
2,2021-10-31,z1e370,1,12,14,1,14,14,85,1,2020-04-22,2020-04-18,9999-99-99,97,2,42,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,1,2,2,97,7,99,México,97,97
3,2021-10-31,z3bf80,2,12,8,2,8,8,37,1,2020-07-28,2020-07-20,9999-99-99,97,2,35,1,97,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
4,2021-10-31,zz7067,1,12,9,2,9,9,7,1,2020-08-18,2020-08-17,9999-99-99,97,2,51,1,97,2,2,2,2,2,2,1,2,2,2,2,2,2,1,2,2,97,7,99,México,97,97

Se seleccionan unicamente los registros que sean confirmados y que sean casos positivos de COVID-19

Según el catalogo de datos, los valores 1,2,3 son casos confirmados

In [5]:
df.columns = ['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'INDIGENA',
       'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'TOMA_MUESTRA_LAB', 'RESULTADO_LAB',
       'TOMA_MUESTRA_ANTIGENO', 'RESULTADO_ANTIGENO', 'CLASIFICACION_FINAL_COVID',
       'MIGRANTE', 'PAIS_NACIONALIDAD', 'PAIS_ORIGEN', 'UCI']

In [6]:
df["CLASIFICACION_FINAL_COVID"].value_counts()

CLASIFICACION_FINAL_COVID
7    1970575
3    1479749
6     259216
1      72091
5      65621
2      11295
4       9849
Name: count, dtype: int64

In [7]:
df[(df["CLASIFICACION_FINAL_COVID"] == 1) | (df["CLASIFICACION_FINAL_COVID"] == 2) | (df["CLASIFICACION_FINAL_COVID"] == 3)]

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,EDAD,NACIONALIDAD,EMBARAZO,HABLA_LENGUA_INDIG,INDIGENA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL_COVID,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-10-31,z4d6fe,1,6,24,1,24,24,28,1,2020-12-06,2020-11-30,9999-99-99,97,2,55,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
3,2021-10-31,z3bf80,2,12,8,2,8,8,37,1,2020-07-28,2020-07-20,9999-99-99,97,2,35,1,97,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
15,2021-10-31,z54912,1,12,31,1,31,31,79,1,2020-06-12,2020-06-10,9999-99-99,97,2,56,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
18,2021-10-31,z552ac,1,12,1,1,9,1,1,1,2020-06-02,2020-05-30,9999-99-99,97,2,58,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
20,2021-10-31,z59345,1,12,31,2,31,31,89,1,2020-07-01,2020-06-30,9999-99-99,97,2,37,1,97,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,97,3,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3868391,2021-10-31,94d648,2,9,9,1,15,15,58,2,2020-12-17,2020-12-14,2020-12-19,2,1,83,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,97,2,97,2,99,México,97,2
3868392,2021-10-31,bb6edb,2,9,9,2,15,15,25,2,2020-04-27,2020-04-15,2020-04-28,2,1,36,1,97,2,2,2,2,2,2,2,2,2,2,2,2,1,2,97,2,97,2,99,México,97,2
3868393,2021-10-31,7d32d9,2,9,9,2,9,9,7,2,2020-12-05,2020-12-01,2020-12-08,1,1,82,1,97,2,2,2,2,2,2,2,2,2,2,2,2,1,2,97,2,97,2,99,México,97,1
3868394,2021-10-31,660ba7,1,4,9,1,9,9,7,2,2020-09-11,2020-09-09,2020-09-12,2,2,40,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,97,2,97,2,99,México,97,2
3868395,2021-10-31,52b2e6,2,4,9,2,9,15,57,2,2020-04-29,2020-04-29,2020-05-14,2,1,48,1,97,2,2,2,2,2,2,1,1,2,2,2,1,2,2,97,2,97,2,99,México,97,2

In [8]:
df = df[(df["CLASIFICACION_FINAL_COVID"] == 1) | (df["CLASIFICACION_FINAL_COVID"] == 2) | (df["CLASIFICACION_FINAL_COVID"] == 3)]

### Se crea una nueva variable que es saber si la persona falleció o no

In [9]:
df["DEFUNCION"] = np.where(df['FECHA_DEF'] == '9999-99-99', 2, 1)

### Se pasa a formato fecha

#### Primero se pasa a nulos los valores de 9999-99-99, que representan lo que no han fallecido

In [10]:
df['FECHA_DEF'] = df['FECHA_DEF'].replace('9999-99-99', np.nan)

In [11]:
df['FECHA_DEF'] = pd.to_datetime(df['FECHA_DEF'])

In [12]:
df['FECHA_INGRESO'] = pd.to_datetime(df['FECHA_INGRESO'])
df['FECHA_SINTOMAS'] = pd.to_datetime(df['FECHA_SINTOMAS'])

Vamos a calcular el numero de dias que han pasado desde la fecha de ingreso/sintomas hasta la fecha de defuncion

In [13]:
df['DIAS_INGRESO_DEF'] = (df['FECHA_DEF'] - df['FECHA_INGRESO']).dt.days
df['DIAS_SINTOMAS_DEF'] = (df['FECHA_DEF'] - df['FECHA_SINTOMAS']).dt.days

In [14]:
df[df['DEFUNCION']== 1][['DIAS_INGRESO_DEF', 'DIAS_SINTOMAS_DEF']]

         DIAS_INGRESO_DEF  DIAS_SINTOMAS_DEF
77                    1.0                4.0
138                   3.0                5.0
159                   0.0                0.0
209                   0.0                6.0
24059                12.0               12.0
...                   ...                ...
3868391               2.0                5.0
3868392               1.0               13.0
3868393               3.0                7.0
3868394               1.0                3.0
3868395              15.0               15.0

[164384 rows x 2 columns]

Seleccionamos las columnas que nos interesan para el análisis

In [15]:
df_cox = df[["DEFUNCION","DIAS_INGRESO_DEF","DIAS_SINTOMAS_DEF", "NEUMONIA", "DIABETES", "EPOC", "ASMA", "INMUSUPR", "HIPERTENSION", "OTRA_COM", "CARDIOVASCULAR", "OBESIDAD", "RENAL_CRONICA", "TABAQUISMO"]]
# df_cox = df[["DEFUNCION","DIAS_INGRESO_DEF","DIAS_SINTOMAS_DEF", "NEUMONIA", "DIABETES", "EPOC", "ASMA", "INMUSUPR", "HIPERTENSION", "OTRA_COM", "CARDIOVASCULAR", "OBESIDAD", "RENAL_CRONICA", "TABAQUISMO", "SEXO"]]

In [16]:
df_cox.head()

,DEFUNCION,DIAS_INGRESO_DEF,DIAS_SINTOMAS_DEF,NEUMONIA,DIABETES,EPOC,ASMA,INMUSUPR,HIPERTENSION,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO
0,2,NaN,NaN,2,1,2,2,2,2,2,2,2,2,2
3,2,NaN,NaN,2,2,2,2,2,2,2,2,2,2,2
15,2,NaN,NaN,2,1,2,2,2,2,2,2,2,2,2
18,2,NaN,NaN,2,1,2,2,2,2,2,2,2,2,2
20,2,NaN,NaN,2,2,2,2,2,2,2,2,2,2,2

In [17]:
df_cox["DEFUNCION"].value_counts()

DEFUNCION
2    1398751
1     164384
Name: count, dtype: int64

Camabiar valores para que 1 sea si (prensenta condicion o afirmacion de nombre de columna) y 0 sea no (no presenta condicion o negación de nombre de columna)

In [18]:
df_cox.replace([1,2], [1,0], inplace=True)

C:\Users\daniel\AppData\Local\Temp\ipykernel_7736\3344868473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cox.replace([1,2], [1,0], inplace=True)

Vamos a eliminar los registros con valores nulos

In [19]:
day_variables = df_cox[["DIAS_INGRESO_DEF","DIAS_SINTOMAS_DEF"]]

In [20]:
df_cox = df_cox.drop(day_variables, axis=1)

In [21]:
df_cox.replace([97,98,99], np.nan, inplace=True)

In [22]:
df_cox = df_cox.dropna()

In [23]:
df_cox["DEFUNCION"].value_counts()

DEFUNCION
0    1390006
1     162084
Name: count, dtype: int64

In [24]:
df_cox = df_cox.astype(int)

In [25]:
df_cox = df_cox.join(day_variables, how='left')

In [26]:
# df.columns

In [27]:
# df_dashboard = df[['SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
#        'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
#        'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'INDIGENA',
#        'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
#        'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO','MIGRANTE', 'PAIS_NACIONALIDAD',
#        'PAIS_ORIGEN', 'UCI', 'DEFUNCION', 'DIAS_INGRESO_DEF',
#        'DIAS_SINTOMAS_DEF']]

In [28]:
# df_dashboard.to_csv('data/df_dashboard.csv', index=False)

In [29]:
# df_cox.to_csv('data/df_cox.csv', index=False)

In [30]:
df_cox.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1552090 entries, 0 to 3868395
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   DEFUNCION          1552090 non-null  int32
 1   NEUMONIA           1552090 non-null  int32
 2   DIABETES           1552090 non-null  int32
 3   EPOC               1552090 non-null  int32
 4   ASMA               1552090 non-null  int32
 5   INMUSUPR           1552090 non-null  int32
 6   HIPERTENSION       1552090 non-null  int32
 7   OTRA_COM           1552090 non-null  int32
 8   CARDIOVASCULAR     1552090 non-null  int32
 9   OBESIDAD           1552090 non-null  int32
 10  RENAL_CRONICA      1552090 non-null  int32
 11  TABAQUISMO         1552090 non-null  int32
 12  DIAS_INGRESO_DEF   162084 non-null   float64
 13  DIAS_SINTOMAS_DEF  162084 non-null   float64
dtypes: float64(2), int32(12)
memory usage: 138.8 MB

In [31]:
df_cox.columns

Index(['DEFUNCION', 'NEUMONIA', 'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR',
       'HIPERTENSION', 'OTRA_COM', 'CARDIOVASCULAR', 'OBESIDAD',
       'RENAL_CRONICA', 'TABAQUISMO', 'DIAS_INGRESO_DEF', 'DIAS_SINTOMAS_DEF'],
      dtype='object')

Se optó por agregar +1 dia a cada registro en las columnas de dias, ya que existen pacientes que fallecieron el mismo dia, por lo que su valor era 0. La regresion cox toma el 0 como un valor representativo de que no ocurrio el evento, entonces por esa razon se tomó la decision de agregar un dia a cada registro.

No se agrego solo a los registros con valor 0 sino un dia a todos los registros con el fin de:

Mantienes la distribución original sin favorecer a los pacientes con 1 día, ya que aumentaria su numero de registros.
Evitas tiempos cero, garantizando que el modelo de Cox funcione sin problemas.
Preservas la representación relativa de los tiempos de evento y censura.

In [32]:
df_cox["DIAS_SINTOMAS_DEF"] = df_cox["DIAS_SINTOMAS_DEF"]+1

In [33]:
df_cox["DIAS_INGRESO_DEF"] = df_cox["DIAS_INGRESO_DEF"]+1

Rellenamos los nulos con valor 0

In [34]:
df_cox.fillna(0, inplace=True)

In [35]:
df_cox = df_cox.astype(int)

In [36]:
df_cox.to_csv('data/df_cox2020.csv', index=False)

In [37]:
# df_cox_hombre = df_cox[df_cox["SEXO"] == 0]
# df_cox_mujer = df_cox[df_cox["SEXO"] == 1]

In [38]:
# df_cox_hombre.to_csv('data/df_cox_hombre.csv', index=False)
# df_cox_mujer.to_csv('data/df_cox_mujer.csv', index=False)